# Generated by Django 6.0 on 2025-12-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_type', models.CharField(choices=[('task', 'Task'), ('bug', 'Bug'), ('feature', 'Feature'), ('pbi', 'Product Backlog Item'), ('epic', 'Epic')], default='task', max_length=20, verbose_name='Тип задачи')),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('closed', 'Closed'), ('new', 'New')], default='new', max_length=20, verbose_name='Статус задачи')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='tasker_app.tag')),
            ],
        ),
    ]
