# Generated by Django 6.0 on 2025-12-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_app', '0003_tag_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('task', 'Задача'), ('bug', 'Баг'), ('feature', 'Функциональность'), ('pbi', 'PBI (Элемент бэклога)'), ('epic', 'Эпик')], default='task', max_length=20, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasker_app.tag'),
        ),
    ]
