# Generated by Django 6.0 on 2025-12-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_app', '0004_task_task_type_alter_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('new', 'New')], default='new', max_length=20, verbose_name='Статус задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('task', 'Task'), ('bug', 'Bug'), ('feature', 'Feature'), ('pbi', 'Product Backlog Item'), ('epic', 'Epic')], default='task', max_length=20, verbose_name='Тип задачи'),
        ),
    ]
